//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearUnusedGUIDs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearUnusedGUIDs.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is available in Family Editor only..
        /// </summary>
        public static string ErrorAvailableOnlyInFamilyEditor {
            get {
                return ResourceManager.GetString("ErrorAvailableOnlyInFamilyEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Parameters file is not set..
        /// </summary>
        public static string ErrorNoSharedParamsFile {
            get {
                return ResourceManager.GetString("ErrorNoSharedParamsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select family-analog.
        /// </summary>
        public static string MessageSelectFamilyAnalog {
            get {
                return ResourceManager.GetString("MessageSelectFamilyAnalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add.
        /// </summary>
        public static string ResultFailedToAdd {
            get {
                return ResourceManager.GetString("ResultFailedToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters succesfully added.
        /// </summary>
        public static string ResultParametersAdded {
            get {
                return ResourceManager.GetString("ResultParametersAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already added.
        /// </summary>
        public static string ResultParamsAlreadyAdded {
            get {
                return ResourceManager.GetString("ResultParamsAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add parameter.
        /// </summary>
        public static string TransactionAddParameter {
            get {
                return ResourceManager.GetString("TransactionAddParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete GUIDs.
        /// </summary>
        public static string TransactionDeleteGuids {
            get {
                return ResourceManager.GetString("TransactionDeleteGuids", resourceCulture);
            }
        }
    }
}
